name: Sync heroku with master
on:
  push:
    branches:
      - master
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge to heroku
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: heroku
          github_token: ${{ github.token }}
